# Generated by Django 4.2.23 on 2025-07-02 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1M', '1 Month'), ('3M', '3 Months'), ('12M', '12 Months')], max_length=3)),
                ('direction', models.FloatField(help_text='Predicted EPS (can be positive or negative)')),
                ('view', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True, help_text='Is this the latest forecast for this analyst/ticker/period?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasts.ticker')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
